// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ68CXBPcWIywUYniphvRtK4WSNTmwfmU',
    appId: '1:894616614717:web:3b96dfa29d901c06d7f754',
    messagingSenderId: '894616614717',
    projectId: 'myapplication-8255fe06',
    authDomain: 'myapplication-8255fe06.firebaseapp.com',
    storageBucket: 'myapplication-8255fe06.firebasestorage.app',
    measurementId: 'G-3KW4MJF63N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIGJhU_gRe-CnXndKDBPUzhMzIXJD3JJE',
    appId: '1:894616614717:android:7ff5fc510bb05d6fd7f754',
    messagingSenderId: '894616614717',
    projectId: 'myapplication-8255fe06',
    storageBucket: 'myapplication-8255fe06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUcaj5MXVbsCRhpUjtgeworGpFXTZGnk',
    appId: '1:894616614717:ios:4f6c840b63b78b1ad7f754',
    messagingSenderId: '894616614717',
    projectId: 'myapplication-8255fe06',
    storageBucket: 'myapplication-8255fe06.firebasestorage.app',
    iosBundleId: 'com.daffa.omrscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUcaj5MXVbsCRhpUjtgeworGpFXTZGnk',
    appId: '1:894616614717:ios:3d226bb3ccc20bf5d7f754',
    messagingSenderId: '894616614717',
    projectId: 'myapplication-8255fe06',
    storageBucket: 'myapplication-8255fe06.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ68CXBPcWIywUYniphvRtK4WSNTmwfmU',
    appId: '1:894616614717:web:7dbf44b3c897969bd7f754',
    messagingSenderId: '894616614717',
    projectId: 'myapplication-8255fe06',
    authDomain: 'myapplication-8255fe06.firebaseapp.com',
    storageBucket: 'myapplication-8255fe06.firebasestorage.app',
    measurementId: 'G-H4LJZ11DWZ',
  );

}